# openai_api_key: "YOUR OPENAI KEY"
openai_api_key: "your_openai_api_key"

# your trello api key and token 
trello_api_key: "your_trello_api_key"
trello_token: "your_trello_token"

# your tmdb access token, kept for future tutorials
tmdb_access_token: "your_tmdb_access_token"
