# A flag to say if want to use this file for configuration
# if true it will use this file else it will use the .env file
use_config_file: true

# openai_api_key: "YOUR OPENAI KEY"
openai_api_key: "your_openai_api_key"

# your trello api key and token 
trello_api_key: "your_trello_api_key"
trello_token: "your_trello_token"

# your tmdb access token, kept for future tutorials
tmdb_access_token: "your_tmdb_access_token"
